-- MySQL Script generated by MySQL Workbench
-- Mon May 11 14:12:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema englishonline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema englishonline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `englishonline` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `englishonline` ;

-- -----------------------------------------------------
-- Table `englishonline`.`baigiang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `englishonline`.`baigiang` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `tenbaigiang` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `mabaigiang` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `noidung` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `englishonline`.`taikhoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `englishonline`.`taikhoan` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `vaitro` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `trangthai` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `englishonline`.`giaovien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `englishonline`.`giaovien` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `hoten` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `taikhoan_id` BIGINT(20) NOT NULL,
  `gioitinh` TINYINT(1) NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `diachi` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `sodienthoai` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_giaovien_taikhoan` (`taikhoan_id` ASC) VISIBLE,
  CONSTRAINT `fk_giaovien_taikhoan`
    FOREIGN KEY (`taikhoan_id`)
    REFERENCES `englishonline`.`taikhoan` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `englishonline`.`khoahoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `englishonline`.`khoahoc` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `tenkhoahoc` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `makhoahoc` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `giaovien_id` BIGINT(20) NOT NULL,
  `capdo` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `anh` TEXT NULL DEFAULT NULL,
  `motangan` TEXT NULL DEFAULT NULL,
  `thoigiantao` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_khoahoc_giaovien` (`giaovien_id` ASC) VISIBLE,
  CONSTRAINT `fk_khoahoc_giaovien`
    FOREIGN KEY (`giaovien_id`)
    REFERENCES `englishonline`.`giaovien` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `englishonline`.`chitietkhoahoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `englishonline`.`chitietkhoahoc` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `khoahoc_id` BIGINT(20) NOT NULL,
  `baigiang_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chitietkhoahoc_khoahoc` (`khoahoc_id` ASC) VISIBLE,
  INDEX `fk_chitietkhoahoc_baigiang` (`baigiang_id` ASC) VISIBLE,
  CONSTRAINT `fk_chitietkhoahoc_baigiang`
    FOREIGN KEY (`baigiang_id`)
    REFERENCES `englishonline`.`baigiang` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_chitietkhoahoc_khoahoc`
    FOREIGN KEY (`khoahoc_id`)
    REFERENCES `englishonline`.`khoahoc` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `englishonline`.`hocvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `englishonline`.`hocvien` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `hoten` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `taikhoan_id` BIGINT(20) NOT NULL,
  `gioitinh` TINYINT(1) NOT NULL,
  `email` VARCHAR(60) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `diachi` VARCHAR(120) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sodienthoai` VARCHAR(11) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hocvien_taikhoan` (`taikhoan_id` ASC) VISIBLE,
  CONSTRAINT `fk_hocvien_taikhoan`
    FOREIGN KEY (`taikhoan_id`)
    REFERENCES `englishonline`.`taikhoan` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `englishonline`.`dangkykhoahoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `englishonline`.`dangkykhoahoc` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `hocvien_id` BIGINT(20) NOT NULL,
  `khoahoc_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dangkykhoahoc_hocvien` (`hocvien_id` ASC) VISIBLE,
  INDEX `fk_dangkykhoahoc_khoahoc` (`khoahoc_id` ASC) VISIBLE,
  CONSTRAINT `fk_dangkykhoahoc_hocvien`
    FOREIGN KEY (`hocvien_id`)
    REFERENCES `englishonline`.`hocvien` (`id`),
  CONSTRAINT `fk_dangkykhoahoc_khoahoc`
    FOREIGN KEY (`khoahoc_id`)
    REFERENCES `englishonline`.`khoahoc` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
